In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
from sklearn.metrics import confusion_matrix
import numpy as np

/home/alison/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
base = pd.read_csv('../datasets/iris.csv')

In [3]:
previsores = base.iloc[:, 0:4].values

In [4]:
classe = base.iloc[:, 4].values

In [5]:
classe

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

## transformando os valores de classe de categóricos para númericos ##

In [6]:
labelencoder = LabelEncoder()

In [7]:
classe = labelencoder.fit_transform(classe)

In [8]:
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

   ## Ainda não esta pronto, as saídas terão três valores, pois são três neuronios de saída, então ## 

   #### iris setosa            1 0 0 ###
   #### iris virginica  0 1 0 ###
   #### iris versicolor 0 0 1 ###


In [9]:
classe_dummy = np_utils.to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

## separando em treinamento e teste ##

In [10]:
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(
    previsores, classe_dummy, test_size= 0.25)

## Criando a rede neural, o units é a quantidade de neuronios na câmada oculta (units),##
## e o cálculo é qtde de colunas + qtde de classe dividido por 2 ##

In [11]:
rede = Sequential()
rede.add(Dense(units = 16, activation = 'relu', input_dim = 4))

# para a segunda camada oculta não é preciso dizer quantas são as camadas de entrada
rede.add(Dense(units = 16, activation = 'relu'))

# camada de saída, cada saída representa uma classe
# problemas de classificação com mais de duas classes é necessário utilizar o softmax
rede.add(Dense(units = 3, activation = 'softmax'))


In [12]:
rede.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])

In [13]:
rede.fit(previsores_treinamento, classe_treinamento, batch_size=10, epochs=1000)

Epoch 1/1000
112/112 [==============================] - 0s 2ms/step - loss: 1.2943 - categorical_accuracy: 0.5982
Epoch 2/1000
112/112 [==============================] - 0s 183us/step - loss: 1.0943 - categorical_accuracy: 0.5625
Epoch 3/1000
112/112 [==============================] - 0s 150us/step - loss: 0.9980 - categorical_accuracy: 0.5536
Epoch 4/1000
112/112 [==============================] - 0s 233us/step - loss: 0.9442 - categorical_accuracy: 0.4554
Epoch 5/1000
112/112 [==============================] - 0s 140us/step - loss: 0.9126 - categorical_accuracy: 0.4107
Epoch 6/1000
112/112 [==============================] - 0s 159us/step - loss: 0.8758 - categorical_accuracy: 0.4732
Epoch 7/1000
112/112 [==============================] - 0s 171us/step - loss: 0.8262 - categorical_accuracy: 0.4911
Epoch 8/1000
112/112 [==============================] - 0s 191us/step - loss: 0.7762 - categorical_accuracy: 0.5446
Epoch 9/1000
112/112 [==============================] - 0s 171us/step - lo

112/112 [==============================] - 0s 150us/step - loss: 0.1205 - categorical_accuracy: 0.9732
Epoch 72/1000
112/112 [==============================] - 0s 159us/step - loss: 0.1313 - categorical_accuracy: 0.9554
Epoch 73/1000
112/112 [==============================] - 0s 126us/step - loss: 0.1173 - categorical_accuracy: 0.9732
Epoch 74/1000
112/112 [==============================] - 0s 134us/step - loss: 0.1211 - categorical_accuracy: 0.9732
Epoch 75/1000
112/112 [==============================] - 0s 129us/step - loss: 0.1187 - categorical_accuracy: 0.9643
Epoch 76/1000
112/112 [==============================] - 0s 124us/step - loss: 0.1158 - categorical_accuracy: 0.9821
Epoch 77/1000
112/112 [==============================] - 0s 156us/step - loss: 0.1289 - categorical_accuracy: 0.9554
Epoch 78/1000
112/112 [==============================] - 0s 147us/step - loss: 0.1141 - categorical_accuracy: 0.9732
Epoch 79/1000
112/112 [==============================] - 0s 137us/step - loss:

112/112 [==============================] - 0s 143us/step - loss: 0.0878 - categorical_accuracy: 0.9732
Epoch 141/1000
112/112 [==============================] - 0s 144us/step - loss: 0.0837 - categorical_accuracy: 0.9732
Epoch 142/1000
112/112 [==============================] - 0s 162us/step - loss: 0.0835 - categorical_accuracy: 0.9732
Epoch 143/1000
112/112 [==============================] - 0s 127us/step - loss: 0.0902 - categorical_accuracy: 0.9732
Epoch 144/1000
112/112 [==============================] - 0s 144us/step - loss: 0.0836 - categorical_accuracy: 0.9732
Epoch 145/1000
112/112 [==============================] - 0s 142us/step - loss: 0.0998 - categorical_accuracy: 0.9554
Epoch 146/1000
112/112 [==============================] - 0s 144us/step - loss: 0.0888 - categorical_accuracy: 0.9732
Epoch 147/1000
112/112 [==============================] - 0s 157us/step - loss: 0.0826 - categorical_accuracy: 0.9732
Epoch 148/1000
112/112 [==============================] - 0s 172us/step

112/112 [==============================] - 0s 195us/step - loss: 0.0741 - categorical_accuracy: 0.9732
Epoch 210/1000
112/112 [==============================] - 0s 154us/step - loss: 0.0813 - categorical_accuracy: 0.9643
Epoch 211/1000
112/112 [==============================] - 0s 230us/step - loss: 0.0745 - categorical_accuracy: 0.9732
Epoch 212/1000
112/112 [==============================] - 0s 145us/step - loss: 0.0748 - categorical_accuracy: 0.9732
Epoch 213/1000
112/112 [==============================] - 0s 154us/step - loss: 0.0738 - categorical_accuracy: 0.9732
Epoch 214/1000
112/112 [==============================] - 0s 148us/step - loss: 0.0781 - categorical_accuracy: 0.9732
Epoch 215/1000
112/112 [==============================] - 0s 155us/step - loss: 0.0746 - categorical_accuracy: 0.9732
Epoch 216/1000
112/112 [==============================] - 0s 129us/step - loss: 0.0731 - categorical_accuracy: 0.9732
Epoch 217/1000
112/112 [==============================] - 0s 143us/step

112/112 [==============================] - 0s 180us/step - loss: 0.0778 - categorical_accuracy: 0.9732
Epoch 279/1000
112/112 [==============================] - 0s 129us/step - loss: 0.0674 - categorical_accuracy: 0.9732
Epoch 280/1000
112/112 [==============================] - 0s 157us/step - loss: 0.0719 - categorical_accuracy: 0.9732
Epoch 281/1000
112/112 [==============================] - 0s 120us/step - loss: 0.0713 - categorical_accuracy: 0.9732
Epoch 282/1000
112/112 [==============================] - 0s 130us/step - loss: 0.0706 - categorical_accuracy: 0.9821
Epoch 283/1000
112/112 [==============================] - 0s 149us/step - loss: 0.0722 - categorical_accuracy: 0.9732
Epoch 284/1000
112/112 [==============================] - 0s 155us/step - loss: 0.0707 - categorical_accuracy: 0.9732
Epoch 285/1000
112/112 [==============================] - 0s 147us/step - loss: 0.0704 - categorical_accuracy: 0.9732
Epoch 286/1000
112/112 [==============================] - 0s 134us/step

112/112 [==============================] - 0s 124us/step - loss: 0.0717 - categorical_accuracy: 0.9732
Epoch 348/1000
112/112 [==============================] - 0s 135us/step - loss: 0.0704 - categorical_accuracy: 0.9821
Epoch 349/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0710 - categorical_accuracy: 0.9732
Epoch 350/1000
112/112 [==============================] - 0s 135us/step - loss: 0.0685 - categorical_accuracy: 0.9732
Epoch 351/1000
112/112 [==============================] - 0s 199us/step - loss: 0.0669 - categorical_accuracy: 0.9732
Epoch 352/1000
112/112 [==============================] - 0s 149us/step - loss: 0.0714 - categorical_accuracy: 0.9732
Epoch 353/1000
112/112 [==============================] - 0s 168us/step - loss: 0.0721 - categorical_accuracy: 0.9643
Epoch 354/1000
112/112 [==============================] - 0s 146us/step - loss: 0.0602 - categorical_accuracy: 0.9821
Epoch 355/1000
112/112 [==============================] - 0s 119us/step

112/112 [==============================] - 0s 176us/step - loss: 0.0693 - categorical_accuracy: 0.9732
Epoch 417/1000
112/112 [==============================] - 0s 170us/step - loss: 0.0684 - categorical_accuracy: 0.9821
Epoch 418/1000
112/112 [==============================] - 0s 120us/step - loss: 0.0636 - categorical_accuracy: 0.9732
Epoch 419/1000
112/112 [==============================] - 0s 133us/step - loss: 0.0671 - categorical_accuracy: 0.9732
Epoch 420/1000
112/112 [==============================] - 0s 140us/step - loss: 0.0664 - categorical_accuracy: 0.9732
Epoch 421/1000
112/112 [==============================] - 0s 127us/step - loss: 0.0652 - categorical_accuracy: 0.9732
Epoch 422/1000
112/112 [==============================] - 0s 138us/step - loss: 0.0684 - categorical_accuracy: 0.9732
Epoch 423/1000
112/112 [==============================] - 0s 129us/step - loss: 0.0649 - categorical_accuracy: 0.9732
Epoch 424/1000
112/112 [==============================] - 0s 131us/step

112/112 [==============================] - 0s 131us/step - loss: 0.0736 - categorical_accuracy: 0.9732
Epoch 486/1000
112/112 [==============================] - 0s 133us/step - loss: 0.0817 - categorical_accuracy: 0.9643
Epoch 487/1000
112/112 [==============================] - 0s 117us/step - loss: 0.0765 - categorical_accuracy: 0.9821
Epoch 488/1000
112/112 [==============================] - 0s 141us/step - loss: 0.0712 - categorical_accuracy: 0.9732
Epoch 489/1000
112/112 [==============================] - 0s 138us/step - loss: 0.0633 - categorical_accuracy: 0.9643
Epoch 490/1000
112/112 [==============================] - 0s 112us/step - loss: 0.0639 - categorical_accuracy: 0.9643
Epoch 491/1000
112/112 [==============================] - 0s 128us/step - loss: 0.0706 - categorical_accuracy: 0.9732
Epoch 492/1000
112/112 [==============================] - 0s 135us/step - loss: 0.0680 - categorical_accuracy: 0.9732
Epoch 493/1000
112/112 [==============================] - 0s 147us/step

112/112 [==============================] - 0s 142us/step - loss: 0.0764 - categorical_accuracy: 0.9732
Epoch 555/1000
112/112 [==============================] - 0s 131us/step - loss: 0.0761 - categorical_accuracy: 0.9554
Epoch 556/1000
112/112 [==============================] - 0s 166us/step - loss: 0.0907 - categorical_accuracy: 0.9732
Epoch 557/1000
112/112 [==============================] - 0s 133us/step - loss: 0.0698 - categorical_accuracy: 0.9732
Epoch 558/1000
112/112 [==============================] - 0s 152us/step - loss: 0.0700 - categorical_accuracy: 0.9821
Epoch 559/1000
112/112 [==============================] - 0s 142us/step - loss: 0.0658 - categorical_accuracy: 0.9643
Epoch 560/1000
112/112 [==============================] - 0s 156us/step - loss: 0.0660 - categorical_accuracy: 0.9643
Epoch 561/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0633 - categorical_accuracy: 0.9821
Epoch 562/1000
112/112 [==============================] - 0s 150us/step

112/112 [==============================] - 0s 172us/step - loss: 0.0629 - categorical_accuracy: 0.9732
Epoch 624/1000
112/112 [==============================] - 0s 155us/step - loss: 0.0875 - categorical_accuracy: 0.9643
Epoch 625/1000
112/112 [==============================] - 0s 198us/step - loss: 0.0635 - categorical_accuracy: 0.9821
Epoch 626/1000
112/112 [==============================] - 0s 142us/step - loss: 0.0667 - categorical_accuracy: 0.9821
Epoch 627/1000
112/112 [==============================] - 0s 159us/step - loss: 0.0606 - categorical_accuracy: 0.9732
Epoch 628/1000
112/112 [==============================] - 0s 130us/step - loss: 0.0644 - categorical_accuracy: 0.9643
Epoch 629/1000
112/112 [==============================] - 0s 120us/step - loss: 0.0625 - categorical_accuracy: 0.9732
Epoch 630/1000
112/112 [==============================] - 0s 186us/step - loss: 0.0611 - categorical_accuracy: 0.9643
Epoch 631/1000
112/112 [==============================] - 0s 138us/step

112/112 [==============================] - 0s 147us/step - loss: 0.0672 - categorical_accuracy: 0.9732
Epoch 693/1000
112/112 [==============================] - 0s 146us/step - loss: 0.0616 - categorical_accuracy: 0.9732
Epoch 694/1000
112/112 [==============================] - 0s 129us/step - loss: 0.0623 - categorical_accuracy: 0.9732
Epoch 695/1000
112/112 [==============================] - 0s 143us/step - loss: 0.0709 - categorical_accuracy: 0.9554
Epoch 696/1000
112/112 [==============================] - 0s 152us/step - loss: 0.0651 - categorical_accuracy: 0.9821
Epoch 697/1000
112/112 [==============================] - 0s 146us/step - loss: 0.0655 - categorical_accuracy: 0.9643
Epoch 698/1000
112/112 [==============================] - 0s 127us/step - loss: 0.0623 - categorical_accuracy: 0.9732
Epoch 699/1000
112/112 [==============================] - 0s 132us/step - loss: 0.0609 - categorical_accuracy: 0.9732
Epoch 700/1000
112/112 [==============================] - 0s 129us/step

112/112 [==============================] - 0s 131us/step - loss: 0.0653 - categorical_accuracy: 0.9821
Epoch 762/1000
112/112 [==============================] - 0s 174us/step - loss: 0.0701 - categorical_accuracy: 0.9732
Epoch 763/1000
112/112 [==============================] - 0s 123us/step - loss: 0.0616 - categorical_accuracy: 0.9732
Epoch 764/1000
112/112 [==============================] - 0s 136us/step - loss: 0.0616 - categorical_accuracy: 0.9821
Epoch 765/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0605 - categorical_accuracy: 0.9732
Epoch 766/1000
112/112 [==============================] - 0s 119us/step - loss: 0.0631 - categorical_accuracy: 0.9732
Epoch 767/1000
112/112 [==============================] - 0s 148us/step - loss: 0.0642 - categorical_accuracy: 0.9732
Epoch 768/1000
112/112 [==============================] - 0s 176us/step - loss: 0.0613 - categorical_accuracy: 0.9732
Epoch 769/1000
112/112 [==============================] - 0s 170us/step

112/112 [==============================] - 0s 151us/step - loss: 0.0601 - categorical_accuracy: 0.9643
Epoch 831/1000
112/112 [==============================] - 0s 154us/step - loss: 0.0642 - categorical_accuracy: 0.9821
Epoch 832/1000
112/112 [==============================] - 0s 139us/step - loss: 0.0652 - categorical_accuracy: 0.9643
Epoch 833/1000
112/112 [==============================] - 0s 146us/step - loss: 0.0579 - categorical_accuracy: 0.9732
Epoch 834/1000
112/112 [==============================] - 0s 112us/step - loss: 0.0678 - categorical_accuracy: 0.9732
Epoch 835/1000
112/112 [==============================] - 0s 132us/step - loss: 0.0881 - categorical_accuracy: 0.9732
Epoch 836/1000
112/112 [==============================] - 0s 137us/step - loss: 0.0914 - categorical_accuracy: 0.9732
Epoch 837/1000
112/112 [==============================] - 0s 138us/step - loss: 0.0734 - categorical_accuracy: 0.9732
Epoch 838/1000
112/112 [==============================] - 0s 119us/step

112/112 [==============================] - 0s 170us/step - loss: 0.0623 - categorical_accuracy: 0.9821
Epoch 900/1000
112/112 [==============================] - 0s 111us/step - loss: 0.0621 - categorical_accuracy: 0.9732
Epoch 901/1000
112/112 [==============================] - 0s 177us/step - loss: 0.0710 - categorical_accuracy: 0.9732
Epoch 902/1000
112/112 [==============================] - 0s 133us/step - loss: 0.0574 - categorical_accuracy: 0.9732
Epoch 903/1000
112/112 [==============================] - 0s 120us/step - loss: 0.0591 - categorical_accuracy: 0.9732
Epoch 904/1000
112/112 [==============================] - 0s 130us/step - loss: 0.0603 - categorical_accuracy: 0.9643
Epoch 905/1000
112/112 [==============================] - 0s 131us/step - loss: 0.0598 - categorical_accuracy: 0.9643
Epoch 906/1000
112/112 [==============================] - 0s 136us/step - loss: 0.0621 - categorical_accuracy: 0.9643
Epoch 907/1000
112/112 [==============================] - 0s 130us/step

112/112 [==============================] - 0s 145us/step - loss: 0.0675 - categorical_accuracy: 0.9732
Epoch 969/1000
112/112 [==============================] - 0s 136us/step - loss: 0.0795 - categorical_accuracy: 0.9643
Epoch 970/1000
112/112 [==============================] - 0s 155us/step - loss: 0.0626 - categorical_accuracy: 0.9732
Epoch 971/1000
112/112 [==============================] - 0s 136us/step - loss: 0.0601 - categorical_accuracy: 0.9643
Epoch 972/1000
112/112 [==============================] - 0s 144us/step - loss: 0.0577 - categorical_accuracy: 0.9732
Epoch 973/1000
112/112 [==============================] - 0s 132us/step - loss: 0.0617 - categorical_accuracy: 0.9643
Epoch 974/1000
112/112 [==============================] - 0s 147us/step - loss: 0.0589 - categorical_accuracy: 0.9732
Epoch 975/1000
112/112 [==============================] - 0s 140us/step - loss: 0.0606 - categorical_accuracy: 0.9732
Epoch 976/1000
112/112 [==============================] - 0s 122us/step

In [14]:
resultado = rede.evaluate(previsores_teste, classe_teste)
resultado

38/38 [==============================] - 0s 913us/step


[0.031626281377516295, 1.0]

In [15]:
previsoes = rede.predict(previsores_teste)
previsoes

array([[9.99998450e-01, 1.57841032e-06, 1.79311405e-12],
       [1.52549524e-06, 9.99832988e-01, 1.65460413e-04],
       [2.07199600e-12, 1.42099219e-04, 9.99857903e-01],
       [9.99996543e-01, 3.43175407e-06, 5.45548199e-12],
       [4.25714035e-07, 9.92699206e-01, 7.30038993e-03],
       [9.99994516e-01, 5.53692416e-06, 9.52348790e-12],
       [9.99978065e-01, 2.19865942e-05, 3.82723714e-11],
       [1.07670962e-06, 9.03849781e-01, 9.61491093e-02],
       [1.41510372e-05, 9.99696016e-01, 2.89782940e-04],
       [3.59570936e-06, 9.95321929e-01, 4.67454083e-03],
       [1.55056725e-07, 6.86496019e-01, 3.13503832e-01],
       [9.99995232e-01, 4.78019592e-06, 1.62678829e-11],
       [4.46220426e-13, 8.19375346e-05, 9.99918103e-01],
       [9.99999762e-01, 2.54865540e-07, 1.08485717e-13],
       [7.84388221e-10, 1.04442136e-02, 9.89555776e-01],
       [9.99994516e-01, 5.47102400e-06, 1.12836520e-11],
       [2.72275761e-11, 1.35812361e-03, 9.98641908e-01],
       [9.99996424e-01, 3.58871

In [16]:
previsoes = (previsoes > 0.5)
previsoes

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [Fa

### Um artifício muito importante é a matriz de confusão, ela nos diz quantos acertos e erros obtive-mos e em quais classes

### aqui ainda dará um erro pois a variáveis previsoes e classe_teste esta em forma de vetor por exemplo: [0 0 1], e para que seja criada uma matriz  de confusão com esses dados é necessário termos uma variável que mostre exatamente o valor que nos interessa, (o índice de maior valor)

In [17]:
matriz = confusion_matrix(previsoes, classe_teste)
matriz

ValueError: multilabel-indicator is not supported

In [18]:
# pegando o maior índice
classe_teste2 = [np.argmax(t) for t in classe_teste]
previsoes2 = [np.argmax(t) for t in previsoes]
print(classe_teste2[:5])
print(previsoes2[:5])

[0, 1, 2, 0, 1]
[0, 1, 2, 0, 1]


In [19]:
# e agora temos o resultado da matriz de confusão, note que em 3x2 temos 3 erros, esse erro só da quando colocamos
# 4 neuronios nas camadas ocultas, mas agora esta com 16 e por isso deu certo 
matriz = confusion_matrix(previsoes2, classe_teste2)
matriz

array([[18,  0,  0],
       [ 0, 12,  0],
       [ 0,  0,  8]])